### ISSUE TITLE
Can't start an angular app

### ISSUE THREAD

**Issue by dcarabott** [fathyb/parcel-plugin-angular#4]
I have a basic hello world angular 5 app. Getting the following error whenever I try to start or build the app: 

```
⚠️  Unexpected identifier
  async getParserOptions() {
        ^^^^^^^^^^^^^^^^
```
**Details**

Node: 6.9.4
Angular: 5.2.3
NPM: 3.10.10
parcel-bundler: 1.5.1
parcel-plugin-angular: 0.5.0

**Comment by fathyb** [comment]
Could you provide a reproduction? Thanks
